// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: telemetry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalCall) Reset() {
	*x = ExternalCall{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCall) ProtoMessage() {}

func (x *ExternalCall) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCall.ProtoReflect.Descriptor instead.
func (*ExternalCall) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *ExternalCall) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"` // "info", "error", "warn", "debug"
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FunctionTrace struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Index           int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	CurrentFunction string                 `protobuf:"bytes,2,opt,name=current_function,json=currentFunction,proto3" json:"current_function,omitempty"`
	ParentFunction  string                 `protobuf:"bytes,3,opt,name=parent_function,json=parentFunction,proto3" json:"parent_function,omitempty"`
	Input           string                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`   // JSON string
	Output          string                 `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"` // JSON string
	LatencyMs       float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	HaveError       bool                   `protobuf:"varint,7,opt,name=have_error,json=haveError,proto3" json:"have_error,omitempty"`
	Logs            []*LogEntry            `protobuf:"bytes,8,rep,name=logs,proto3" json:"logs,omitempty"`
	ExternalCalls   []*ExternalCall        `protobuf:"bytes,9,rep,name=external_calls,json=externalCalls,proto3" json:"external_calls,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FunctionTrace) Reset() {
	*x = FunctionTrace{}
	mi := &file_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionTrace) ProtoMessage() {}

func (x *FunctionTrace) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionTrace.ProtoReflect.Descriptor instead.
func (*FunctionTrace) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *FunctionTrace) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FunctionTrace) GetCurrentFunction() string {
	if x != nil {
		return x.CurrentFunction
	}
	return ""
}

func (x *FunctionTrace) GetParentFunction() string {
	if x != nil {
		return x.ParentFunction
	}
	return ""
}

func (x *FunctionTrace) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *FunctionTrace) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *FunctionTrace) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *FunctionTrace) GetHaveError() bool {
	if x != nil {
		return x.HaveError
	}
	return false
}

func (x *FunctionTrace) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *FunctionTrace) GetExternalCalls() []*ExternalCall {
	if x != nil {
		return x.ExternalCalls
	}
	return nil
}

type PushMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ProcessType   string                 `protobuf:"bytes,2,opt,name=process_type,json=processType,proto3" json:"process_type,omitempty"` // "api", "cron", "consumer"
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsSuccessful  bool                   `protobuf:"varint,5,opt,name=is_successful,json=isSuccessful,proto3" json:"is_successful,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ExecutionFlow []*FunctionTrace       `protobuf:"bytes,7,rep,name=execution_flow,json=executionFlow,proto3" json:"execution_flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMetricRequest) Reset() {
	*x = PushMetricRequest{}
	mi := &file_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMetricRequest) ProtoMessage() {}

func (x *PushMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMetricRequest.ProtoReflect.Descriptor instead.
func (*PushMetricRequest) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *PushMetricRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *PushMetricRequest) GetProcessType() string {
	if x != nil {
		return x.ProcessType
	}
	return ""
}

func (x *PushMetricRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PushMetricRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *PushMetricRequest) GetIsSuccessful() bool {
	if x != nil {
		return x.IsSuccessful
	}
	return false
}

func (x *PushMetricRequest) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *PushMetricRequest) GetExecutionFlow() []*FunctionTrace {
	if x != nil {
		return x.ExecutionFlow
	}
	return nil
}

type PushMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMetricResponse) Reset() {
	*x = PushMetricResponse{}
	mi := &file_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMetricResponse) ProtoMessage() {}

func (x *PushMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMetricResponse.ProtoReflect.Descriptor instead.
func (*PushMetricResponse) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *PushMetricResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PushMetricResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushMetricResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\ttelemetry\" \n" +
	"\fExternalCall\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"X\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xce\x02\n" +
	"\rFunctionTrace\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12)\n" +
	"\x10current_function\x18\x02 \x01(\tR\x0fcurrentFunction\x12'\n" +
	"\x0fparent_function\x18\x03 \x01(\tR\x0eparentFunction\x12\x14\n" +
	"\x05input\x18\x04 \x01(\tR\x05input\x12\x16\n" +
	"\x06output\x18\x05 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"have_error\x18\a \x01(\bR\thaveError\x12'\n" +
	"\x04logs\x18\b \x03(\v2\x13.telemetry.LogEntryR\x04logs\x12>\n" +
	"\x0eexternal_calls\x18\t \x03(\v2\x17.telemetry.ExternalCallR\rexternalCalls\"\x98\x02\n" +
	"\x11PushMetricRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fprocess_type\x18\x02 \x01(\tR\vprocessType\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12#\n" +
	"\ris_successful\x18\x05 \x01(\bR\fisSuccessful\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x01R\tlatencyMs\x12?\n" +
	"\x0eexecution_flow\x18\a \x03(\v2\x18.telemetry.FunctionTraceR\rexecutionFlow\"g\n" +
	"\x12PushMetricResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2]\n" +
	"\x10TelemetryService\x12I\n" +
	"\n" +
	"PushMetric\x12\x1c.telemetry.PushMetricRequest\x1a\x1d.telemetry.PushMetricResponseB/Z-github.com/Rajneesh100/kril/backend/pkg/telemetry/pbb\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_telemetry_proto_goTypes = []any{
	(*ExternalCall)(nil),       // 0: telemetry.ExternalCall
	(*LogEntry)(nil),           // 1: telemetry.LogEntry
	(*FunctionTrace)(nil),      // 2: telemetry.FunctionTrace
	(*PushMetricRequest)(nil),  // 3: telemetry.PushMetricRequest
	(*PushMetricResponse)(nil), // 4: telemetry.PushMetricResponse
}
var file_telemetry_proto_depIdxs = []int32{
	1, // 0: telemetry.FunctionTrace.logs:type_name -> telemetry.LogEntry
	0, // 1: telemetry.FunctionTrace.external_calls:type_name -> telemetry.ExternalCall
	2, // 2: telemetry.PushMetricRequest.execution_flow:type_name -> telemetry.FunctionTrace
	3, // 3: telemetry.TelemetryService.PushMetric:input_type -> telemetry.PushMetricRequest
	4, // 4: telemetry.TelemetryService.PushMetric:output_type -> telemetry.PushMetricResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
